version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
      - "9108:9108"

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
