name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm -r exec tsc --noEmit

      - name: Lint
        run: pnpm lint

      - name: Unit and integration tests
        run: pnpm test

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: latest

      - name: Foundry tests
        run: forge test

      - name: Slither
        uses: crytic/slither-action@v0.3.1
        with:
          target: contracts

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
